name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  publish:
    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Release Gem
        uses: CvX/publish-rubygems-action@master
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}